"""Context helper usage: replies, typing indicators, reactions, attachments, and locks."""

from __future__ import annotations

import asyncio
import base64

from signal_client import Context, SignalClient
from signal_client.command import command
from signal_client.infrastructure.schemas.link_preview import LinkPreview
from signal_client.infrastructure.schemas.requests import SendMessageRequest

_balances: dict[str, int] = {}


@command("!echo")
async def echo(ctx: Context) -> None:
    await ctx.start_typing()
    try:
        text = ctx.message.message or ""
        await ctx.reply(
            SendMessageRequest(message=f"echo: {text}", recipients=[])
        )
    finally:
        await ctx.stop_typing()


@command("!react")
async def react(ctx: Context) -> None:
    await ctx.react("👍")
    # Remove the reaction after acknowledging.
    await ctx.remove_reaction()


@command("!share")
async def share(ctx: Context) -> None:
    payload = SendMessageRequest(
        message="Attachment + mention + preview",
        recipients=[],
        base64_attachments=[base64.b64encode(b"hello from signal-client").decode()],
        mentions=[
            {
                "number": ctx.message.source,
                "length": len(ctx.message.message or ""),
                "offset": 0,
            }
        ],
        preview=LinkPreview(
            url="https://example.com",
            title="Example",
            description="Preview generated by signal-client",
        ),
    )
    await ctx.send(payload)


@command("!balance")
async def balance(ctx: Context) -> None:
    user = ctx.message.source
    async with ctx.lock(f"balance:{user}"):
        current = _balances.get(user, 100)
        _balances[user] = current + 10
        await ctx.reply(
            SendMessageRequest(
                message=f"Balance for {user}: {_balances[user]}",
                recipients=[],
            )
        )


async def main() -> None:
    async with SignalClient() as bot:
        bot.register(echo)
        bot.register(react)
        bot.register(share)
        bot.register(balance)
        await bot.start()


if __name__ == "__main__":
    asyncio.run(main())
