"""Context helper usage: replies, typing indicators, reactions, attachments, and locks."""

from __future__ import annotations

import asyncio
import base64

from signal_client import Context, SignalClient
from signal_client.command import command
from signal_client.infrastructure.schemas.requests import MessageMention

_balances: dict[str, int] = {}


@command("!echo")
async def echo(ctx: Context) -> None:
    await ctx.show_typing()
    try:
        text = ctx.message.message or ""
        await ctx.reply_text(f"echo: {text}")
    finally:
        await ctx.hide_typing()


@command("!react")
async def react(ctx: Context) -> None:
    await ctx.react("👍")
    # Remove the reaction after acknowledging.
    await ctx.remove_reaction()


@command("!share")
async def share(ctx: Context) -> None:
    mention_text = ctx.message.source
    message_text = f"Attachment + mention of {mention_text}"
    mention_start = message_text.index(mention_text)
    await ctx.send_text(
        message_text,
        base64_attachments=[base64.b64encode(b"hello from signal-client").decode()],
        mentions=[
            MessageMention(
                author=mention_text,
                start=mention_start,
                length=len(mention_text),
            )
        ],
    )
    await ctx.send_with_preview(
        "https://example.com",
        title="Example",
        description="Preview generated by signal-client",
    )


@command("!balance")
async def balance(ctx: Context) -> None:
    user = ctx.message.source
    async with ctx.lock(f"balance:{user}"):
        current = _balances.get(user, 100)
        _balances[user] = current + 10
        await ctx.reply_text(f"Balance for {user}: {_balances[user]}")


async def main() -> None:
    async with SignalClient() as bot:
        bot.register(echo)
        bot.register(react)
        bot.register(share)
        bot.register(balance)
        await bot.start()


if __name__ == "__main__":
    asyncio.run(main())
